# Generated by Django 5.2.8 on 2025-11-15 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cne",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="user",
            name="capacity_kg",
            field=models.PositiveIntegerField(
                default=10, validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
