# Generated by Django 5.2.8 on 2025-11-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_cne_user_phone_alter_user_capacity_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
