# Generated by Django 5.2.9 on 2025-12-29 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_cne_user_phone_alter_user_capacity_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="capacity_kg",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
