# Generated by Django 5.2.8 on 2025-11-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FRUIT", "Fruit"),
                            ("VEGETABLE", "Vegetable"),
                            ("PREPARED", "Prepared Food"),
                        ],
                        max_length=16,
                    ),
                ),
                ("unit", models.CharField(default="unit", max_length=16)),
                ("weight_per_unit_kg", models.FloatField(default=1.0)),
            ],
        ),
    ]
