# Generated by Django 5.2.8 on 2025-11-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_store"),
        ("orders", "0002_order_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="catalog.store",
            ),
        ),
    ]
